@startuml Pig(Dice)
Game --> DiceHand
Game --> Player
Player --> DiceHand
Player --> Intelligence
Intelligence --> DiceHand
DiceHand --> Dice
Game --> Histogram
Game --> Highscore
EasyAI <|-- Intelligence
NormalAI <|-- Intelligence
HardAI <|-- Intelligence
Human <|-- Intelligence
class Dice {
    -sides : int
    -rolls_made : int
    -sum_of_all_rolls : int
    +set_sides(int sides) : void
    +roll_die() : int
    +get_rolls_made() : int
    +get_sum_of_all_rolls() : int
}
class Player {
    -name : str
    -total_score : int
    -turn_score : int
    -is_ai : bool
    +add_turn_points(int pts) : void
    +bank_turn() : void
    +lose_turn() : void
    +reset() : void
    +__repr__() : str
}
abstract class Intelligence {
    +decide_action() : int
}
class EasyAI {
    +decide_action() : int
}
class NormalAI {
    +decide_action() : int
}
class HardAI {
    +decide_action() : int
}
class Human {
    +decide_action() : int
}
@enduml